-- 코드를 입력하세요
-- USER INFO 테이블과 온라인 상품 판매 정보를 담은 ONLINE_SALE 테이블
-- USER INFO, 회원 ID, 성별,나이,가입일
-- GENDER는 비어있거나 0 또는 1 의 값
-- ONLINE_SALE 테이블은 상품판매 ID, 회원ID, 상품 ID, 판매량, 판매일 




SELECT YEAR(O.SALES_DATE) YEAR,
MONTH(O.SALES_DATE) MONTH,
I.GENDER,
COUNT(DISTINCT(O.USER_ID)) USERS FROM ONLINE_SALE AS O
JOIN (SELECT USER_ID, GENDER FROM USER_INFO 
WHERE GENDER IS NOT NULL) AS I
ON I.USER_ID = O.USER_ID
GROUP BY YEAR(O.SALES_DATE),MONTH(O.SALES_DATE),I.GENDER
ORDER BY YEAR(O.SALES_DATE),MONTH(O.SALES_DATE),I.GENDER

# SELECT 
#     LEFT(ONL.SALES_DATE,4)AS YEAR
#     ,MID(ONL.SALES_DATE,6,2)AS MONTH
#      ,USER.GENDER
#      ,COUNT(DISTINCT(ONL.PRODUCT_ID)) AS USERS
# FROM USER_INFO AS USER 
# RIGHT JOIN ONLINE_SALE AS ONL
# ON USER.USER_ID = ONL.USER_ID
# WHERE USER.GENDER IS NOT NULL 
# GROUP BY YEAR ,MONTH, USER.GENDER
# ORDER BY YEAR,MONTH,USER.GENDER