-- 코드를 입력하세요
-- 의류 쇼핑몰에 가입한 회원 정보
-- GENDER 컬럼은 비어있거나 0 또는 1의 값을 가지며 0인경우 남자를, 1인 경우 여자를
-- 테이블 USER_INFO , ONLINE_SALE



SELECT YEAR(O.SALES_DATE) YEAR,
MONTH(O.SALES_DATE) MONTH,
COUNT(distinct(O.USER_ID)) PUCHASED_USERS,
ROUND(COUNT(distinct(O.USER_ID))/(SELECT COUNT(I.USER_ID) FROM USER_INFO I WHERE YEAR(I.JOINED)=2021) ,1) PUCHASED_RATIO 
FROM ONLINE_SALE O
LEFT JOIN (SELECT I.USER_ID,I.JOINED FROM USER_INFO AS I
            WHERE YEAR(I.JOINED) = 2021
           ) I ON O.USER_ID = I.USER_ID WHERE YEAR(I.JOINED) = 2021
GROUP BY YEAR(O.SALES_DATE),MONTH(O.SALES_DATE)
ORDER BY YEAR(O.SALES_DATE),MONTH(O.SALES_DATE)

# SELECT   
#     YEAR(S.SALES_DATE)AS YEAR
#     ,MONTH(S.SALES_DATE)AS MONTH
#     ,(COUNT(DISTINCT(S.USER_ID))) AS PUCHASED_USERS
#     ,ROUND(((COUNT(DISTINCT(S.USER_ID)))/(SELECT COUNT(USER_ID) FROM USER_INFO WHERE YEAR(JOINED)=2021)),1)AS PUCHASED_RATIO
# FROM ONLINE_SALE AS S
# LEFT JOIN USER_INFO AS U 
# ON S.USER_ID = U.USER_ID
# WHERE YEAR(U.JOINED) = 2021 
# GROUP BY YEAR,MONTH
# ORDER BY YEAR,MONTH