-- 코드를 입력하세요
-- 2021년에 가입한 전체 회원들 중 상품을 구매한 회원수와 상품을 구매한 회원의 비율을 년,월 별로 출력하는 SQL문



SELECT 
YEAR(O.SALES_DATE) YEAR,MONTH(O.SALES_DATE) MONTH,
COUNT(DISTINCT(O.USER_ID)) AS PUCHASED_USERS,
ROUND(
    (COUNT(DISTINCT(O.USER_ID)))
    /
    (SELECT COUNT(USER_ID) FROM USER_INFO WHERE YEAR(JOINED)=2021), 1)   

# COUNT(O.USER_ID) PUCHASED_USERS,
# COUNT(O.USER_ID)/SUM(U.USER_ID) PUCHASED_RATIO 
FROM ONLINE_SALE O
JOIN
(SELECT USER_ID FROM USER_INFO WHERE YEAR(JOINED)=2021) 
AS U ON U.USER_ID = O.USER_ID
GROUP BY YEAR(SALES_DATE),MONTH(SALES_DATE)
ORDER BY SALES_DATE