-- 코드를 입력하세요
SELECT A.CATEGORY, A.PRICE MAX_PRICE, A.PRODUCT_NAME FROM FOOD_PRODUCT A 
JOIN (SELECT CATEGORY,MAX(PRICE) PRICE,PRODUCT_NAME FROM FOOD_PRODUCT
GROUP BY CATEGORY) AS B
ON A.CATEGORY = B.CATEGORY AND A.PRICE=B.PRICE
WHERE A.CATEGORY IN ('과자','국','김치','식용유')
ORDER BY B.PRICE DESC

# SELECT A.CATEGORY, A.PRICE, A.PRODUCT_NAME
# FROM FOOD_PRODUCT A JOIN (
#     SELECT CATEGORY, PRODUCT_NAME, MAX(PRICE) AS PRICE
#     FROM FOOD_PRODUCT
#     GROUP BY CATEGORY
# ) B
# ON A.CATEGORY = B.CATEGORY AND A.PRICE = B.PRICE 
# WHERE A.CATEGORY IN ('과자', '국', '김치', '식용유')
# ORDER BY B.PRICE DESC