-- 코드를 입력하세요
SELECT P.PRODUCT_CODE, (P.PRICE*O.SALES_AMOUNT) SALES FROM PRODUCT P 
JOIN (SELECT O.PRODUCT_ID , SUM(O.SALES_AMOUNT) SALES_AMOUNT FROM OFFLINE_SALE O
GROUP BY O.PRODUCT_ID) AS O
ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY O.PRODUCT_ID
ORDER BY SALES DESC, P.PRODUCT_CODE ASC
